# Generated by Django 5.2.7 on 2025-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_type',
            field=models.CharField(choices=[('Light', 'Light'), ('Lock', 'Lock'), ('Camera', 'Camera')], max_length=20),
        ),
    ]
