# Generated by Django 5.2.7 on 2025-10-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_status_title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=3)),
            ],
        ),
    ]
