# Generated by Django 5.2.7 on 2025-10-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lightstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightstatus',
            old_name='light_status_title',
            new_name='light_name',
        ),
    ]
